WITH YEAR_CNT AS (
    SELECT YEAR(YM) AS YM, COUNT(*) AS CNT, 
    SUM(PM_VAL1) AS PM1, 
    SUM(PM_VAL2) AS PM2 
    FROM AIR_POLLUTION 
    WHERE LOCATION2 = '수원' 
    GROUP BY YEAR(YM)
)

SELECT YM AS YEAR, ROUND(PM1/CNT, 2) AS PM10, ROUND(PM2/CNT, 2) AS 'PM2.5'
FROM YEAR_CNT GROUP BY YM ORDER BY 1;