-- CAR_ID, CAR_TYPE, DAILY_FEE, OPTIONS
-- 자동차 ID, 자동차 종류, 일일 대여 요금(원), 자동차 옵션 리스트
SELECT CAR_TYPE, COUNT(*) AS CARS FROM CAR_RENTAL_COMPANY_CAR 
    WHERE OPTIONS LIKE '%시트%'
    GROUP BY CAR_TYPE ORDER BY 1;