SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM (
    SELECT * FROM APPOINTMENT WHERE DATE(APNT_YMD) = '2022-04-13' AND APNT_CNCL_YN = 'N' AND MCDP_CD = 'CS') AS A 
    JOIN ( SELECT DR_NAME, DR_ID FROM DOCTOR WHERE MCDP_CD = 'CS') AS D ON A.MDDR_ID = D.DR_ID 
    JOIN PATIENT AS P ON A.PT_NO = P.PT_NO
ORDER BY A.APNT_YMD;