WITH GRADE as 
(
    SELECT EMP_NO, SUM(SCORE) AS SCORE 
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT G.SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL 
FROM GRADE G JOIN HR_EMPLOYEES E ON G.EMP_NO = E.EMP_NO
WHERE G.SCORE = (SELECT MAX(SCORE) FROM GRADE);