WITH GRADE as 
(
    SELECT EMP_NO, SUM(SCORE) AS SCORE 
    FROM HR_GRADE
    GROUP BY EMP_NO
)

# SELECT * FROM GRADE;
SELECT G.SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL FROM GRADE G JOIN HR_EMPLOYEES E ON G.EMP_NO = E.EMP_NO
WHERE G.SCORE = (SELECT MAX(SCORE) FROM GRADE);

-- HR_DEPARTMENT 테이블
-- DEPT_ID, DEPT_NAME_KR, DEPT_NAME_EN, LOCATION
-- 부서 ID, 국문 부서명, 영문 부서명, 부서 위치

-- HR_EMPLOYEES 테이블
-- EMP_NO, EMP_NAME, DEPT_ID, POSITION, EMAIL, COMP_TEL, HIRE_DATE, SAL
-- 사번, 성명, 부서 ID, 직책, 이메일, 전화번호, 입사일, 연봉
